(function() {var implementors = {};
implementors["base64"] = [{"text":"impl&lt;'a, R:&nbsp;Read&gt; Read for DecoderReader&lt;'a, R&gt;","synthetic":false,"types":[]}];
implementors["bytes"] = [{"text":"impl&lt;B:&nbsp;Buf + Sized&gt; Read for Reader&lt;B&gt;","synthetic":false,"types":[]}];
implementors["futures_util"] = [{"text":"impl&lt;T&gt; Read for AllowStdIo&lt;T&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;T: Read,&nbsp;</span>","synthetic":false,"types":[]}];
implementors["hyper"] = [{"text":"impl&lt;S:&nbsp;NetworkStream&gt; Read for PooledStream&lt;S&gt;","synthetic":false,"types":[]},{"text":"impl Read for Response","synthetic":false,"types":[]},{"text":"impl&lt;'a&gt; Read for Body&lt;'a&gt;","synthetic":false,"types":[]},{"text":"impl Read for Http11Message","synthetic":false,"types":[]},{"text":"impl&lt;R:&nbsp;Read&gt; Read for HttpReader&lt;R&gt;","synthetic":false,"types":[]},{"text":"impl Read for HttpStream","synthetic":false,"types":[]},{"text":"impl&lt;S:&nbsp;NetworkStream&gt; Read for HttpsStream&lt;S&gt;","synthetic":false,"types":[]},{"text":"impl&lt;'a, 'b&gt; Read for Request&lt;'a, 'b&gt;","synthetic":false,"types":[]}];
implementors["mio"] = [{"text":"impl Read for TcpStream","synthetic":false,"types":[]},{"text":"impl&lt;'a&gt; Read for &amp;'a TcpStream","synthetic":false,"types":[]}];
implementors["mio_uds"] = [{"text":"impl Read for UnixStream","synthetic":false,"types":[]},{"text":"impl&lt;'a&gt; Read for &amp;'a UnixStream","synthetic":false,"types":[]}];
implementors["openssl"] = [{"text":"impl&lt;S:&nbsp;Read + Write&gt; Read for SslStream&lt;S&gt;","synthetic":false,"types":[]}];
implementors["postgres"] = [{"text":"impl&lt;'_&gt; Read for CopyOutReader&lt;'_&gt;","synthetic":false,"types":[]}];
implementors["rand_core"] = [{"text":"impl Read for dyn RngCore","synthetic":false,"types":[]}];
implementors["rocket"] = [{"text":"impl Read for NamedFile","synthetic":false,"types":[]},{"text":"impl&lt;'a&gt; Read for &amp;'a NamedFile","synthetic":false,"types":[]},{"text":"impl Read for DataStream","synthetic":false,"types":[]}];
if (window.register_implementors) {window.register_implementors(implementors);} else {window.pending_implementors = implementors;}})()