stages:
 - test
 - build

cache:
  key: ${CI_JOB_NAME}
  paths:
    - api/target/release

test:
  stage: test
  image: rust:latest
  script:
    - rustup default nightly
    - cargo test --release

build:
  stage: build
  image: rust:latest
  script:
    - rustup default nightly
    - cargo build --release
