[package]
name = "potatosync-rust"
version = "0.1.0"
authors = ["bas"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diesel = { version = "1.4.5", features = ["postgres", "r2d2", "chrono"] }
rocket = { version = "0.4.5", default-features = false }
serde = "1.0"
serde_json = "*"
serde_derive = "*"
serde_with = "*"
chrono = { version = "0.4.9", features = ["serde"] }
chrono-tz = "0.5.2"
diesel_migrations = "1.4.0"
rocket_failure = { version = "0.2" }
dotenv = "0.15.0"
validator = "0.10"
validator_derive = "0.10"
lazy_static = "1.4.0"
openssl = "*"
uuid = { version = "0.8", features = ["serde", "v4"] }
jsonwebtoken = "7.2.0"

[dependencies.rocket_contrib]
version = "*"
default-features = false
features = ["json"]

[dev-dependencies]
mocktopus = "0.7.0"
