[package]
name = "potatosync-rust"
version = "0.1.0"
authors = ["bas"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diesel = { version = "1.4.0", features = ["postgres", "r2d2", "chrono"] }
rocket = { version = "0.4.2", default-features = false }
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
serde_with = "1.4.0"
chrono = { version = "0.4.9", features = ["serde"] }
chrono-tz = "0.4"
rayon = "1.3.0"
diesel_migrations = "1.4.0"
rocket_failure = { version="0.1", features = ["with-rocket"] }
dotenv = "0.10.1"
validator = "0.10"
validator_derive = "0.10"
lazy_static = "1.4.0"
openssl = "*"
uuid = { version = "0.8", features = ["serde", "v4"] }
regex = "1.3.9"
tokkit = "0.17.0"
reqwest = "*"

[dependencies.rocket_contrib]
version = "*"
default-features = false
features = ["json"]

[dev-dependencies]
mocktopus = "0.7.0"
