name: Docker
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: whoan/docker-build-with-cache-action@v5
        name: Build AMD64 Image
        with:
          username: basmakes
          password: "${{ secrets.DOCKER_PASSWORD }}"
          image_name: basmakes/potatosync-notes
          image_tag: amd64
          dockerfile: amd64.Dockerfile
