name: Docker
on:
  push:
    branches:
      - master

jobs:
  build-amd64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: whoan/docker-build-with-cache-action@v5
        name: Build AMD64 Image
        with:
          username: basmakes
          password: "${{ secrets.DOCKER_PASSWORD }}"
          image_name: basmakes/potatosync-notes
          image_tag: amd64
          dockerfile: amd64.Dockerfile
  build-arm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: whoan/docker-build-with-cache-action@v5
        name: Build ARM Image
        with:
          username: basmakes
          password: "${{ secrets.DOCKER_PASSWORD }}"
          image_name: basmakes/potatosync-notes
          image_tag: arm
          dockerfile: rpi.Dockerfile
