name: Docker
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup docker
        uses: docker-practice/actions-setup-docker@0.0.1
      - name: Docker Buildx
        uses: crazy-max/ghaction-docker-buildx@v1.0.5
      - name: Build and push docker image
        env:
          DOCKER_USERNAME: basmakes
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo Logging Into Docker
          docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
          echo Installing BuildX
          update-binfmts --enable
          docker buildx create --driver docker-container --use
          docker buildx inspect --bootstrap
          docker buildx ls
          echo Building Containers and Publishing them
          docker pull potatosync-rust:arm || true
          docker buildx build --cache-from basmakes/potatosync-rust:arm --platform linux/arm --progress plain --pull -t "basmakes/potatosync-rust:arm" -f rpi.Dockerfile --push .
          docker pull potatosync-rust:amd64 || true
          docker buildx build --cache-from basmakes/potatosync-rust:amd64 --platform linux/amd64 --progress plain --pull -t "basmakes/potatosync-rust:amd64" -f amd64.Dockerfile --push .