name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: nightly
      - uses: actions/checkout@master
      - uses: harmon758/postgresql-action@v1
        with:
          postgresql db: 'notes'
          postgresql user: 'notes'
          postgresql password: 'notes'
      - name: Create .env
        run: mv sample.env .env
      - name: Cache Rust dependencies
        uses: actions/cache@v1
        with:
          path: target
          key: rust-test
      - name: Run cargo test
        run: cargo test
  publish-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: nightly
      - uses: actions/checkout@master
      - name: Run cargo doc
        run: cargo doc
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/doc/
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup docker
        uses: docker-practice/actions-setup-docker@0.0.1
      - name: Docker Buildx
        uses: crazy-max/ghaction-docker-buildx@v1.0.5
      - name: Build and push docker image
        env:
          DOCKER_USERNAME: basmakes
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo Logging Into Docker
          docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
          echo Installing BuildX
          update-binfmts --enable
          docker buildx create --driver docker-container --use
          docker buildx inspect --bootstrap
          docker buildx ls
          echo Building Containers and Publishing them
          docker buildx build --platform linux/arm,linux/arm64,linux/amd64 --progress plain --pull -t "basmakes/potatosync-rust" --push .
