name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and Publish docker image
      uses: whoan/docker-build-with-cache-action@v4
      with:
        # Registry username
        username: basmakes
        # Registry password
        password: ${{ secrets.DOCKER_PASSWORD }}
        # Repository on registry
        image_name: basmakes/potatosync-rust
