name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Docker Action
      uses: zenato/docker-action@v1.0.0
      with:
        # Registry username
        username: basmakes
        # Registry password
        password: ${{ secrets.DOCKER_PASSWORD }}
        # Repository on registry
        repository: basmakes/potatosync-rust
        # Image tag
        tag: latest
