on:
  push:
  pull_request:

jobs:
  cargo-test:
    runs-on: ubuntu-latest
    steps:
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: nightly
      - uses: actions/checkout@master
      - uses: harmon758/postgresql-action@v1
        with:
          postgresql db: 'notes'
          postgresql user: 'notes'
          postgresql password: 'notes'
      - name: Create .env
        run: mv sample.env .env
      - name: Cache cargo build
        uses: actions/cache@v1
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}
      - name: Run cargo test
        run: cargo test